---
default_time_series_variables:
  - net_electricity_consumption
  - net_electricity_consumption_without_storage
  - net_electricity_consumption_without_storage_and_partial_load
  - net_electricity_consumption_without_storage_and_partial_load_and_pv
  - solar_generation
  - cooling_electricity_consumption
  - heating_electricity_consumption
  - dhw_electricity_consumption
  - non_shiftable_load_electricity_consumption
  - cooling_storage_electricity_consumption
  - heating_storage_electricity_consumption
  - dhw_storage_electricity_consumption
  - electrical_storage_electricity_consumption
  - cooling_demand
  - cooling_demand_without_partial_load
  - heating_demand
  - heating_demand_without_partial_load
  - dhw_demand
  - non_shiftable_load
  - energy_from_cooling_device
  - energy_from_heating_device
  - energy_from_dhw_device
  - energy_from_cooling_storage
  - energy_from_heating_storage
  - energy_from_dhw_storage
  - energy_from_electrical_storage
  - energy_from_cooling_device_to_cooling_storage
  - energy_from_heating_device_to_heating_storage
  - energy_from_dhw_device_to_dhw_storage
  - energy_to_non_shiftable_load
  - energy_to_electrical_storage
  - cooling_device_cop
  - heating_device_cop
  - dhw_device_cop
  - cooling_storage.soc
  - heating_storage.soc
  - dhw_storage.soc
  - electrical_storage.soc
  - indoor_dry_bulb_temperature
  - indoor_dry_bulb_temperature_without_partial_load
  - energy_simulation.indoor_dry_bulb_temperature_set_point
  - energy_simulation.occupant_count
  - pricing.electricity_pricing
  - carbon_intensity.carbon_intensity
  - energy_simulation.power_outage
  - weather.outdoor_dry_bulb_temperature
  - weather.outdoor_relative_humidity
...